apiVersion: v2
name: bitbucket
description: A chart for installing Bitbucket Data Center on Kubernetes
type: application
version: 0.13.0
appVersion: 7.12.1-jdk11
kubeVersion: ">=1.19.x-0"
keywords:
  - Bitbucket
  - Bitbucket Server
  - Bitbucket Data Center
  - Bitbucket DC
  - Atlassian
home: https://www.atlassian.com/software/bitbucket
icon: https://atlassian-labs.github.io/data-center-helm-charts/icons/bitbucket.svg
sources:
  - https://github.com/atlassian-labs/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-atlassian-bitbucket-server/
deprecated: false
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Bitbucket NFS server chart
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/205
    - kind: changed
      description: Volume docs updates
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/188