apiVersion: v2
name: bitbucket
description: A chart for installing Bitbucket Data Center on Kubernetes
type: application
version: 1.10.1
appVersion: 7.21.10
kubeVersion: ">=1.21.x-0"
keywords:
- Bitbucket
- Bitbucket Server
- Bitbucket Data Center
- Bitbucket DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/bitbucket.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-bitbucket-server/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Release/1.10.0 (#519)
    - "DCCLIP-350: Add Bitbucket Mesh to Bitbucket Helm chart (#501)"

dependencies:
- name: common
  version: 1.0.0
  repository: https://atlassian.github.io/data-center-helm-charts
