apiVersion: v2
name: bitbucket
description: A chart for installing Bitbucket Data Center on Kubernetes
type: application
version: 0.15.0
appVersion: 7.15.1-jdk11
kubeVersion: ">=1.19.x-0"
keywords:
  - Bitbucket
  - Bitbucket Server
  - Bitbucket Data Center
  - Bitbucket DC
  - Atlassian
home: https://www.atlassian.com/software/bitbucket
icon: https://atlassian-labs.github.io/data-center-helm-charts/icons/bitbucket.svg
sources:
  - https://github.com/atlassian-labs/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-atlassian-bitbucket-server/
deprecated: false
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Add support for providing a custom fluentd start command
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/218
    - kind: changed
      description: Make some deployment params configurable
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/226
    - kind: changed
      description: Renamed the 'master' branch to 'main'
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/232
    - kind: changed
      description: Update eks cluster yaml
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/227
    - kind: changed
      description: Improve documentation
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/206
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/222
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/223
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/228
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/229
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/231
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/233
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/235
