apiVersion: v2
name: bitbucket
description: A chart for installing Bitbucket Data Center on Kubernetes
type: application
version: '2.0.6'
appVersion: 9.4.12
kubeVersion: ">=1.21.x-0"
keywords:
- Bitbucket
- Bitbucket Server
- Bitbucket Data Center
- Bitbucket DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/bitbucket.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-bitbucket-server/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "fix: Added default Kubernetes parameters to VolumeClaimTemplate to prevent infinite DRIFT (#1030)"

dependencies:
- name: common
  version: 1.2.7
  repository: https://atlassian.github.io/data-center-helm-charts
- name: opensearch
  version: 2.19.0
  repository: https://opensearch-project.github.io/helm-charts
  condition: opensearch.install
