apiVersion: v2
name: bitbucket
description: A chart for installing Bitbucket Data Center on Kubernetes
type: application
version: '1.18'
appVersion: 8.9.10
kubeVersion: ">=1.21.x-0"
keywords:
- Bitbucket
- Bitbucket Server
- Bitbucket Data Center
- Bitbucket DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/bitbucket.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-bitbucket-server/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Add Openshift analytics (#763)"
    - "Update appVersions for DC apps (#765)"
    - "OpenShift Support (#752)"
    - "Use testPods values for test images and container resources (#761)"
    - "Relabel instance name on jmx service monitor (#757)"
    - "Added pvc retention policy to Bitbucket Mesh StatefulSet (#755)"

dependencies:
- name: common
  version: 1.2.6
  repository: https://atlassian.github.io/data-center-helm-charts
