apiVersion: v2
name: bitbucket
description: A chart for installing Bitbucket Data Center on Kubernetes
type: application
version: 1.0.0
appVersion: 7.15.1-jdk11
kubeVersion: ">=1.19.x-0"
keywords:
  - Bitbucket
  - Bitbucket Server
  - Bitbucket Data Center
  - Bitbucket DC
  - Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/bitbucket.svg
sources:
  - https://github.com/atlassian/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-atlassian-bitbucket-server/
deprecated: false
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Enable NFS permission fixer by default
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/241
    - kind: changed
      description: Provide value for set permissions
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/261
    - kind: added
      description: Configurable grace periods
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/249
    - kind: changed
      description: Update the Bitbucket image name, as the '-server' suffix is now deprecated
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/259
    - kind: changed
      description: Improve documentation
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/236
        url: https://github.com/atlassian/data-center-helm-charts/pull/243
        url: https://github.com/atlassian/data-center-helm-charts/pull/245
        url: https://github.com/atlassian/data-center-helm-charts/pull/252
        url: https://github.com/atlassian/data-center-helm-charts/pull/253
        url: https://github.com/atlassian/data-center-helm-charts/pull/256
        url: https://github.com/atlassian/data-center-helm-charts/pull/258
        url: https://github.com/atlassian/data-center-helm-charts/pull/260
        url: https://github.com/atlassian/data-center-helm-charts/pull/268
