apiVersion: v2
name: bitbucket
description: A chart for installing Bitbucket Data Center on Kubernetes
type: application
version: 1.14.0
appVersion: 8.9.3
kubeVersion: ">=1.21.x-0"
keywords:
- Bitbucket
- Bitbucket Server
- Bitbucket Data Center
- Bitbucket DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/bitbucket.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-bitbucket-server/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Add liveness probes, make readinessProbes configurable (#626)"
    - "make sharedHome.permissionFix.command helper to be per-product (#622)"

dependencies:
- name: common
  version: 1.2.3
  repository: https://atlassian.github.io/data-center-helm-charts
