apiVersion: v2
name: bitbucket
description: A chart for installing Bitbucket Data Center on Kubernetes
type: application
version: 1.0.0
appVersion: 7.15.1-jdk11
kubeVersion: ">=1.19.x-0"
keywords:
  - Bitbucket
  - Bitbucket Server
  - Bitbucket Data Center
  - Bitbucket DC
  - Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/bitbucket.svg
sources:
  - https://github.com/atlassian/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-atlassian-bitbucket-server/
deprecated: false
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Improve graceful shutdown
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/282
    - kind: changed
      description: Use the AWS LB Controller with ALB/NLBs instead of nginx for testing
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/294
    - kind: changed
      description: Improve documentation
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/275
        url: https://github.com/atlassian/data-center-helm-charts/pull/276
        url: https://github.com/atlassian/data-center-helm-charts/pull/277
        url: https://github.com/atlassian/data-center-helm-charts/pull/279
        url: https://github.com/atlassian/data-center-helm-charts/pull/280
        url: https://github.com/atlassian/data-center-helm-charts/pull/284
        url: https://github.com/atlassian/data-center-helm-charts/pull/285
        url: https://github.com/atlassian/data-center-helm-charts/pull/289
        url: https://github.com/atlassian/data-center-helm-charts/pull/290
        url: https://github.com/atlassian/data-center-helm-charts/pull/291
        url: https://github.com/atlassian/data-center-helm-charts/pull/293
        url: https://github.com/atlassian/data-center-helm-charts/pull/295