apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-jvm-config
  labels:
    {{- include "common.labels.commonLabels" . | nindent 4 }}
data:
  additional_jvm_args: >-
    {{- range .Values.bitbucket.additionalJvmArgs }}
    {{ . }}
    {{- end }}
    -XX:ActiveProcessorCount={{ include "flooredCPU" .Values.bitbucket.resources.container.requests.cpu }}
    {{ include "common.jmx.javaagent" . | indent 4 | trim }}
    {{- if .Values.monitoring.exposeJmxMetrics }}
    -Dplugin.bitbucket-git.mesh.sidecar.jvmArgs=-javaagent:{{ .Values.monitoring.jmxExporterCustomJarLocation | default (printf "%s/jmx_prometheus_javaagent.jar"  .Values.volumes.sharedHome.mountPath) }}=9998:/opt/atlassian/jmx/jmx-config.yaml
    {{- end }}
    {{- if .Values.bitbucket.additionalCertificates.secretName }}
    -Djavax.net.ssl.trustStore=/var/ssl/cacerts
    {{- end }}
  max_heap: {{ .Values.bitbucket.resources.jvm.maxHeap }}
  min_heap: {{ .Values.bitbucket.resources.jvm.minHeap }}
