apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-jvm-config-mesh
  labels:
    {{- include "common.labels.commonLabels" . | nindent 4 }}
data:
  additional_jvm_args: >-
    {{- range .Values.bitbucket.mesh.additionalJvmArgs }}
    {{ . }}
    {{- end }}
    -XX:ActiveProcessorCount={{ include "flooredCPU" .Values.bitbucket.mesh.resources.container.requests.cpu }}
    {{- if .Values.monitoring.exposeJmxMetrics }}
    -javaagent:{{ .Values.monitoring.jmxExporterCustomJarLocation | default (printf "%s/jmx_prometheus_javaagent.jar" ( .Values.bitbucket.mesh.volume.mountPath)) }}={{ .Values.monitoring.jmxExporterPort}}:/opt/atlassian/jmx/jmx-config.yaml
    {{- end }}
    {{- if .Values.bitbucket.mesh.additionalCertificates.secretName }}
    -Djavax.net.ssl.trustStore=/var/ssl/cacerts
    {{- end }}
  max_heap: {{ .Values.bitbucket.mesh.resources.jvm.maxHeap }}
  min_heap: {{ .Values.bitbucket.mesh.resources.jvm.minHeap }}
