{{- if .Values.volumes.sharedHome.nfsPermissionFixer.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "bitbucket.fullname" . }}-nfs-fixer
  labels:
    {{- include "bitbucket.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  template:
    metadata:
      name: {{ include "bitbucket.fullname" . }}-nfs-fixer
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bitbucket.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: nfs-fixer
          image: alpine
          securityContext:
            runAsUser: 0 # make sure we run as root so we get the ability to change the volume permissions
          volumeMounts:
            - name: shared-home
              mountPath: {{ .Values.volumes.sharedHome.nfsPermissionFixer.mountPath | quote }}
              {{- if .Values.volumes.sharedHome.subPath }}
              subPath: {{ .Values.volumes.sharedHome.subPath | quote }}
              {{- end }}
          command: ["sh", "-c", {{ include "sharedHome.permissionFix.command" . | quote }}]
      volumes:
        {{ include "bitbucket.volumes.sharedHome" . | nindent 8 }}
{{- end }}