{{/*This describes a K8s service for comunicating with the statefulset*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitbucket.fullname" . }}
  labels:
    {{- include "bitbucket.labels" . | nindent 4 }}
spec:
  type: {{ .Values.bitbucket.service.type }}
  ports:
    - port: {{ .Values.bitbucket.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.bitbucket.ports.ssh }}
      targetPort: ssh
      protocol: TCP
      name: ssh
    - port: {{ .Values.bitbucket.ports.hazelcast }}
      targetPort: hazelcast
      protocol: TCP
      name: hazelcast
  selector:
    {{- include "bitbucket.selectorLabels" . | nindent 4 }}
