{{- if .Values.volumes.sharedHome.persistentVolumeClaim.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bitbucket.fullname" . }}-shared-home
  labels:
  {{- include "bitbucket.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.volumes.sharedHome.persistentVolumeClaim.accessMode }}
  {{- if not (kindIs "invalid" .Values.volumes.sharedHome.persistentVolumeClaim.storageClassName) }}
  storageClassName: {{ .Values.volumes.sharedHome.persistentVolumeClaim.storageClassName | quote }}
  {{- end }}
  {{- if .Values.volumes.sharedHome.persistentVolume.create }}
  volumeName: {{ include "bitbucket.volume.sharedHome.name" . }}
  {{- else}}
  volumeName: {{ .Values.volumes.sharedHome.persistentVolumeClaim.volumeName | quote }}
  {{- end }}
  {{- with .Values.volumes.sharedHome.persistentVolumeClaim.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}
