apiVersion: v2
name: bamboo-agent
description: A chart for installing Bamboo Data Center remote agents on Kubernetes
type: application
version: 1.3.0
appVersion: 8.1.3
kubeVersion: ">=1.19.x-0"
keywords:
  - Bamboo
  - Bamboo Agent
  - Bamboo Data Center
  - Bamboo DC
  - Atlassian
home: https://www.atlassian.com/software/bamboo
icon: https://atlassian.github.io/data-center-helm-charts/icons/bamboo.svg
sources:
  - https://github.com/atlassian/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-bamboo-agent-base
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - kind: changed
      description: Bamboo Agent updated to 8.1.3 version
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/396
dependencies:
  - name: common
    version: 1.0.0
    repository: https://atlassian.github.io/data-center-helm-charts