apiVersion: v2
name: bamboo-agent
description: A chart for installing Bamboo Data Center remote agents on Kubernetes
type: application
version: 1.7.0
appVersion: 9.0.0
kubeVersion: ">=1.19.x-0"
keywords:
  - Bamboo
  - Bamboo Agent
  - Bamboo Data Center
  - Bamboo DC
  - Atlassian
home: https://www.atlassian.com/software/bamboo
icon: https://atlassian.github.io/data-center-helm-charts/icons/bamboo.svg
sources:
  - https://github.com/atlassian/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-bamboo-agent-base
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - kind: changed
      description: Pin Python version to 3.9.14
      links:
        - name: Github PR
          url: https://github.com/atlassian/data-center-helm-charts/pull/468
    - kind: changed
      description: Update Bitbucket ingress testing values
      links:
        - name: Github PR
          url: https://github.com/atlassian/data-center-helm-charts/pull/466
    - kind: changed
      description: Ingress Class Name is moved under spec field.
      links:
        - name: Github PR
          url: https://github.com/atlassian/data-center-helm-charts/pull/451
    - kind: changed
      description: CLIP-1520: Make ATL_FORCE_CFG_UPDATE configurable
      in values.yaml
      links:
        - name: Github PR
          url: https://github.com/atlassian/data-center-helm-charts/pull/454
    - kind: changed
      description: Add osquery related env vars for Terraform
      links:
        - name: Github PR
          url: https://github.com/atlassian/data-center-helm-charts/pull/462
    - kind: changed
      description: AWS cleanup and log colletion from k8s
      links:
        - name: Github PR
          url: https://github.com/atlassian/data-center-helm-charts/pull/461
    - kind: changed
      description: Update the index for release 1.6.0

dependencies:
  - name: common
    version: 1.0.0
    repository: https://atlassian.github.io/data-center-helm-charts
