apiVersion: v2
name: bamboo-agent
description: A chart for installing Bamboo Data Center remote agents on Kubernetes
type: application
version: 1.17.2
appVersion: 9.4.2
kubeVersion: ">=1.21.x-0"
keywords:
- Bamboo
- Bamboo Agent
- Bamboo Data Center
- Bamboo DC
- Atlassian
home: https://www.atlassian.com/software/bamboo
icon: https://atlassian.github.io/data-center-helm-charts/icons/bamboo.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-bamboo-agent-base
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "StatefulSet PVC auto deletion (#736)"
    - "Update appVersions for DC apps (#738)"
dependencies:
- name: common
  version: 1.2.5
  repository: https://atlassian.github.io/data-center-helm-charts
