apiVersion: v2
name: crowd
description: A chart for installing Crowd Data Center on Kubernetes
type: application
version: 1.3.0
appVersion: 5.0.0
kubeVersion: ">=1.19.x-0"
keywords:
  - Crowd
  - Crowd Server
  - Crowd Data Center
  - Crowd DC
  - Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/crowd.svg
sources:
  - https://github.com/atlassian/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-atlassian-crowd/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - kind: added
      description: Make pod securityContext optional
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/389
    - kind: added
      description: Support for configuring ingress proxy settings via values.yaml
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/402
    - kind: fixed
      description: Fixed common.label error 
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/403
    - kind: changed
      description: Update Crowd version to 5.0.0
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/412
dependencies:
  - name: common
    version: 1.0.0
    repository: https://atlassian.github.io/data-center-helm-charts
