apiVersion: v2
name: crowd
description: A chart for installing Crowd Data Center on Kubernetes
type: application
version: '2.0.4'
appVersion: 6.3.1
kubeVersion: ">=1.21.x-0"
keywords:
- Crowd
- Crowd Server
- Crowd Data Center
- Crowd DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/crowd.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-crowd/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "fix: Update Bitnami image references due to deprecation notice (#1037)"

dependencies:
- name: common
  version: 1.2.7
  repository: https://atlassian.github.io/data-center-helm-charts
