apiVersion: v2
name: crowd
description: A chart for installing Crowd Data Center on Kubernetes
type: application
version: '1.22.0'
appVersion: 6.1.1
kubeVersion: ">=1.21.x-0"
keywords:
- Crowd
- Crowd Server
- Crowd Data Center
- Crowd DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/crowd.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-crowd/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Updated pod labels for all products (#901)"
    - "Fix shutdown with jmx javaagent enabled (#899)"
    - "Unset IDs for all the Grafana dashboards (#889)"

dependencies:
- name: common
  version: 1.2.7
  repository: https://atlassian.github.io/data-center-helm-charts
