apiVersion: v2
name: crowd
description: A chart for installing Crowd Data Center on Kubernetes
type: application
version: 1.15.3
appVersion: 5.1.4
kubeVersion: ">=1.21.x-0"
keywords:
- Crowd
- Crowd Server
- Crowd Data Center
- Crowd DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/crowd.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-crowd/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Decouple server and jmx annotations (#654)"
    - "Disable startup probes by default (#653)"

dependencies:
- name: common
  version: 1.2.3
  repository: https://atlassian.github.io/data-center-helm-charts
