apiVersion: v2
name: crowd
description: A chart for installing Crowd Data Center on Kubernetes
type: application
version: 1.12.0
appVersion: 5.1.2
kubeVersion: ">=1.21.x-0"
keywords:
- Crowd
- Crowd Server
- Crowd Data Center
- Crowd DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/crowd.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-crowd/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Add priorityClassName to pod spec (#557)"
    - "Add hostAliases for all DC products (#556)"
    - "Crowd service type edge case documentation (#554)"
    - "Add a warning to Crowd's values.yaml ingress.path field (#550)"
    - "Update fluentd cm template for crowd (#547)"
    - "Documentation for Crowd (#544)"

dependencies:
- name: common
  version: 1.2.0
  repository: https://atlassian.github.io/data-center-helm-charts
