apiVersion: v2
name: crowd
description: A chart for installing Crowd Data Center on Kubernetes
type: application
version: 1.17.1
appVersion: 5.2.1
kubeVersion: ">=1.21.x-0"
keywords:
- Crowd
- Crowd Server
- Crowd Data Center
- Crowd DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/crowd.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-crowd/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Make liveness probe configurable (#732)"

dependencies:
- name: common
  version: 1.2.5
  repository: https://atlassian.github.io/data-center-helm-charts
