---
apiVersion: v1
kind: Service
metadata:
  name: bamboo-agent
  labels:
    app: bamboo-agent
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: bamboo-agent
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bamboo-agent
spec:
  selector:
    matchLabels:
      app: bamboo-agent # has to match .spec.template.metadata.labels
  serviceName: bamboo-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: bamboo-agent # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 2005
      initContainers:
        - name: copy-bamboo-capabilities
          image: alpine
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /home/bamboo/bamboo-agent-home/bin
              name: bamboo-agent-local-home-bin
            - mountPath: /bamboo-capabilities
              name: capabilities
          command: ['sh', '-c', 'cp /bamboo-capabilities/bamboo-capabilities.properties /home/bamboo/bamboo-agent-home/bin']
      containers:
        - name: bamboo-agent
          image: dchevell/bamboo-base-agent
          env:
            - name: BAMBOO_SERVER
              value: "https://bamboo-k8s.deplops.com"
            - name: SECURITY_TOKEN
              value: "77a97f9fda63111c631a23aefb6a068fd8a71004"
            - name: WRAPPER_JAVA_INITMEMORY
              value: "256"
            - name: WRAPPER_JAVA_MAXMEMORY
              value: "512"
          volumeMounts:
            - mountPath: /home/bamboo/bamboo-agent-home
              name: bamboo-agent-local-home
            - mountPath: /home/bamboo/bamboo-agent-home/bin
              name: bamboo-agent-local-home-bin
      volumes:
        - name: capabilities
          configMap:
            name: capabilities
  volumeClaimTemplates:
    - metadata:
        name: bamboo-agent-local-home
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "bamboo-local-home"
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: bamboo-agent-local-home-bin
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "bamboo-local-home"
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: capabilities
data:
  bamboo-capabilities.properties: |
    "system.jdk.JDK 1.8" /opt/java/openjdk/bin/java
    "system.git.executable" /usr/bin/git