apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bamboo-agent-local-home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: bamboo-local-home
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bamboo-agent-local-home-bin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: bamboo-local-home
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bamboo-agent
  labels:
    app: bamboo-agent
spec:
  selector:
    matchLabels:
      app: bamboo-agent 
  replicas: 1
  template:
    metadata:
      labels:
        app: bamboo-agent 
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
        - name: bamboo-agent
          image: atlassian/bamboo-agent-base
          args: [ "https://bamboo-k8s.deplops.com" ]
          env:
            - name: VM_OPTS
              value: "-Dwrapper.java.initmemory=512 -Dwrapper.java.maxmemory=2048"
          volumeMounts:
            - mountPath: /home/bamboo/bamboo-agent-home
              name: bamboo-agent-local-home
            - mountPath: /home/bamboo/bamboo-agent-home/bin
              name: bamboo-agent-local-home-bin
      volumes:
        - name: bamboo-agent-local-home
          persistentVolumeClaim:
            claimName: "bamboo-agent-local-home"
        - name: bamboo-agent-local-home-bin
          persistentVolumeClaim:
            claimName: "bamboo-agent-local-home-bin"

    