apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-jvm-config
  labels:
    {{- include "common.labels.commonLabels" . | nindent 4 }}
data:
  additional_jvm_args: >-
    {{ include "confluence.sysprop.hazelcastListenPort" . }}
    {{ include "confluence.sysprop.synchronyServiceUrl" . }}
    {{ include "confluence.sysprop.enable.synchrony.by.default" . }}
    {{ include "confluence.sysprop.clusterNodeName" . }}
    {{ include "confluence.sysprop.fluentdAppender" . }}
    {{- include "confluence.sysprop.debug" . -}}
    {{- range .Values.confluence.additionalJvmArgs }}
    {{ . }}
    {{- end }}
    -XX:ActiveProcessorCount={{ max 1 (include "flooredCPU" .Values.confluence.resources.container.requests.cpu | float64  | int) }}
    {{- if .Values.serviceAccount.eksIrsa.roleArn }}
    -Daws.webIdentityTokenFile=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
    {{- end }}
    {{- if or .Values.confluence.additionalCertificates.secretName .Values.confluence.additionalCertificates.secretList }}
    -Djavax.net.ssl.trustStore=/var/ssl/cacerts
    {{- end }}
    {{- include "confluence.sysprop.s3Config" . | indent 4 }}
    {{- if .Values.opensearch.enabled }}
    -Dsearch.platform=opensearch
    -Dopensearch.http.url=http://opensearch-cluster-master:9200
    -Dopensearch.username=admin
    -Dopensearch.password={{ include "opensearch.initial.admin.password" . | b64dec -}}
    {{- end }}
    {{- if .Values.confluence.tunnel.additionalConnector.port }}
    -Dsecure.tunnel.upstream.port={{ .Values.confluence.tunnel.additionalConnector.port }}
    {{- end }}
  max_heap: {{ .Values.confluence.resources.jvm.maxHeap }}
  min_heap: {{ .Values.confluence.resources.jvm.minHeap }}
  reserved_code_cache: {{ .Values.confluence.resources.jvm.reservedCodeCache }}
