apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "confluence.fullname" . }}-jvm-config
  labels:
    {{- include "confluence.labels" . | nindent 4 }}
data:
  additional_jvm_args: >-
    {{ include "confluence.sysprop.hazelcastListenPort" . }}
    {{ include "confluence.sysprop.synchronyServiceUrl" . }}
    {{ include "confluence.sysprop.clusterNodeName" . }}
    {{ include "confluence.sysprop.fluentdAppender" . }}
    {{- range .Values.confluence.additionalJvmArgs }}
    {{ . }}
    {{- end }}
  max_heap: {{ .Values.confluence.resources.jvm.maxHeap }}
  min_heap: {{ .Values.confluence.resources.jvm.minHeap }}
  reserved_code_cache: {{ .Values.confluence.resources.jvm.reservedCodeCache }}
