apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-jvm-config
  labels:
    {{- include "common.labels.commonLabels" . | nindent 4 }}
data:
  additional_jvm_args: >-
    {{ include "confluence.sysprop.hazelcastListenPort" . }}
    {{ include "confluence.sysprop.synchronyServiceUrl" . }}
    {{ include "confluence.sysprop.enable.synchrony.by.default" . }}
    {{ include "confluence.sysprop.clusterNodeName" . }}
    {{ include "confluence.sysprop.fluentdAppender" . }}
    {{- include "confluence.sysprop.debug" . -}}
    {{- range .Values.confluence.additionalJvmArgs }}
    {{ . }}
    {{- end }}
    -XX:ActiveProcessorCount={{ include "flooredCPU" .Values.confluence.resources.container.requests.cpu }}
    {{- if .Values.serviceAccount.eksIrsa.roleArn }}
    -Daws.webIdentityTokenFile=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
    {{- end }}
    {{- if .Values.confluence.additionalCertificates.secretName }}
    -Djavax.net.ssl.trustStore=/var/ssl/cacerts
    {{- end }}
    {{- include "common.jmx.javaagent" . | indent 4 -}}
    {{- include "confluence.sysprop.s3Config" . | indent 4 }}
  max_heap: {{ .Values.confluence.resources.jvm.maxHeap }}
  min_heap: {{ .Values.confluence.resources.jvm.minHeap }}
  reserved_code_cache: {{ .Values.confluence.resources.jvm.reservedCodeCache }}
