{{- if .Values.ingress.create }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "confluence.fullname" . }}
  labels:
    {{- include "confluence.labels" . | nindent 4 }}
  annotations:
    {{ if .Values.ingress.nginx }}
    "kubernetes.io/ingress.class": "nginx"
    "nginx.ingress.kubernetes.io/affinity": "cookie"
    "nginx.ingress.kubernetes.io/affinity-mode": "persistent"
    "nginx.ingress.kubernetes.io/proxy-body-size": {{ .Values.ingress.maxBodySize }}
    "nginx.ingress.kubernetes.io/proxy-connect-timeout": "60"
    "nginx.ingress.kubernetes.io/proxy-read-timeout": "60"
    "nginx.ingress.kubernetes.io/proxy-send-timeout": "60"
    {{- end }}
    {{- with .Values.ingress.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{ if and (.Values.ingress.tlsSecretName) (.Values.ingress.host) }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
{{ end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ include "confluence.ingressPath" . }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "confluence.fullname" . }}
                port:
                  number: {{ $.Values.confluence.service.port }}
          {{ if .Values.synchrony.enabled }}
          - path: {{ trimSuffix "/" (include "confluence.ingressPath" .) }}/synchrony
            pathType: Prefix
            backend:
              service:
                name: {{ include "synchrony.fullname" . }}
                port:
                  number: {{ $.Values.synchrony.service.port }}
          {{ end }}
{{ end }}