apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.commonLabels" . | nindent 4 }}
  annotations:
    {{- with .Values.confluence.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.confluence.service.type }}
  sessionAffinity: {{ .Values.confluence.service.sessionAffinity }}
  {{- if .Values.confluence.service.sessionAffinityConfig.clientIP.timeoutSeconds }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.confluence.service.sessionAffinityConfig.clientIP.timeoutSeconds }}
  {{- end }}
  {{- if and (eq .Values.confluence.service.type "LoadBalancer") (not (empty .Values.confluence.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.confluence.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.confluence.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if not .Values.confluence.hazelcastService.enabled }}
    - port: {{ .Values.confluence.ports.hazelcast }}
      targetPort: hazelcast
      protocol: TCP
      name: hazelcast
  {{- end }}
  selector:
    {{- include "common.labels.selectorLabels" . | nindent 4 }}
