apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.commonLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "common.names.fullname" . }}
  selector:
    matchLabels:
      {{- include "common.labels.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config-jvm: {{ include (print $.Template.BasePath "/config-jvm.yaml") . | sha256sum }}
        {{- if .Values.additionalConfigMaps }}
        checksum/config-additional: {{ include (print $.Template.BasePath "/configmap-additional-config.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.fluentd.enabled }}
        checksum/config-fluentd: {{ include (print $.Template.BasePath "/configmap-fluentd.yaml") . | sha256sum }}
        {{- end }}
        {{- include "confluence.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "common.labels.selectorLabels" . | nindent 8 }}
        {{- include "confluence.podLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "confluence.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.confluence.shutdown.terminationGracePeriodSeconds }}
      {{- if .Values.confluence.securityContextEnabled }}
      {{- with .Values.confluence.securityContext }}
      securityContext:
        {{/* this condition will be removed in v2.0.0 */}}
        {{- if and .enabled .gid }}
        fsGroup: {{ .gid }}
        {{- else }}
        {{ toYaml . | nindent 8 }}
        {{- if not .fsGroup }}
        fsGroup: 2002
        {{- end }}
        {{- end }}
      {{- end }}
      {{- end }}
      hostAliases:
        {{- include "confluence.additionalHosts" . | nindent 8 }}
      initContainers:
        {{- include "confluence.additionalInitContainers" . | nindent 8 }}
        {{- if .Values.volumes.sharedHome.nfsPermissionFixer.enabled }}
        - name: nfs-permission-fixer
          image: {{ .Values.volumes.sharedHome.nfsPermissionFixer.imageRepo }}:{{ .Values.volumes.sharedHome.nfsPermissionFixer.imageTag }}
          imagePullPolicy: IfNotPresent
          {{- if .Values.volumes.sharedHome.nfsPermissionFixer.resources }}
          resources:
          {{- with .Values.volumes.sharedHome.nfsPermissionFixer.resources }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          securityContext:
            runAsUser: 0 # make sure we run as root so we get the ability to change the volume permissions
          volumeMounts:
            - name: shared-home
              mountPath: {{ .Values.volumes.sharedHome.nfsPermissionFixer.mountPath | quote }}
              {{- if .Values.volumes.sharedHome.subPath }}
              subPath: {{ .Values.volumes.sharedHome.subPath | quote }}
              {{- end }}
          command: ["sh", "-c", {{ include "confluence.sharedHome.permissionFix.command" . | quote }}]
        {{- end }}
        {{- include "common.jmx.initContainer" . | nindent 8 }}
        {{- if .Values.confluence.additionalCertificates.secretName }}
        - name: import-certs
          image: {{ include "confluence.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: keystore
              mountPath: /var/ssl
            - name: certs
              mountPath: /tmp/crt
          command: ["/bin/bash"]
          args: ["-c", {{ include "confluence.addCrtToKeystoreCmd" . }}]
        {{- end }}
      containers:
        - name: {{ if .Values.confluence.useHelmReleaseNameAsContainerName}}{{ include "common.names.fullname" . }}{{ else }}{{ .Chart.Name }}{{ end }}
          image: {{ include "confluence.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.confluence.ports.http }}
              protocol: TCP
            - name: hazelcast
              containerPort: {{ .Values.confluence.ports.hazelcast }}
              protocol: TCP
            {{- include "common.jmx.port" . | nindent 12 }}
            {{- include "confluence.additionalPorts" . | nindent 12 }}
          {{- if .Values.confluence.readinessProbe.enabled }}
          readinessProbe:
            {{- if .Values.confluence.readinessProbe.customProbe}}
            {{- with .Values.confluence.readinessProbe.customProbe }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- else }}
            httpGet:
              port: {{ .Values.confluence.ports.http }}
              path: {{ .Values.confluence.service.contextPath }}/status
            initialDelaySeconds: {{ .Values.confluence.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.confluence.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.confluence.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.confluence.readinessProbe.failureThreshold }}
            {{- end }}
          {{- end }}
          {{- if .Values.confluence.startupProbe.enabled }}
          startupProbe:
            tcpSocket:
              port: {{ .Values.confluence.ports.http }}
            initialDelaySeconds: {{ .Values.confluence.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.confluence.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.confluence.startupProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.confluence.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.confluence.ports.http }}
            initialDelaySeconds: {{ .Values.confluence.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.confluence.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.confluence.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.confluence.livenessProbe.failureThreshold }}
          {{ end }}
          {{- with .Values.confluence.containerSecurityContext}}
          securityContext:
          {{- toYaml . | nindent 12}}
          {{- end}}
          {{- with .Values.confluence.resources.container }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- include "confluence.volumeMounts" . | nindent 12 }}
            {{- include "common.jmx.config.volumeMounts" . | nindent 12 }}
            {{- include "confluence.additionalVolumeMounts" . | nindent 12 }}
            {{- include "confluence.additionalLibraries" . | nindent 12 }}
            {{- include "confluence.additionalBundledPlugins" . | nindent 12 }}
            {{- range $i, $n := .Values.additionalFiles }}
            - name: {{ .name }}-{{$i}}
              mountPath: {{ .mountPath }}/{{ .key }}
              subPath: {{ .key }}
            {{ end }}
            {{- range $i, $n := .Values.additionalConfigMaps }}
            {{- range .keys }}
            - name: {{ .fileName | replace "_" "-" | replace "." "-" }}
              mountPath: {{ .mountPath }}/{{ .fileName }}
              subPath: {{ .fileName }}
            {{ end }}
            {{- end }}
          env:
            {{ if .Values.ingress.https }}
            - name: ATL_TOMCAT_SCHEME
              value: "https"
            - name: ATL_TOMCAT_SECURE
              value: "true"
            {{ end }}
            {{ if .Values.confluence.service.contextPath }}
            - name: ATL_TOMCAT_CONTEXTPATH
              value: {{ .Values.confluence.service.contextPath | quote }}
            {{ end }}
            - name: ATL_TOMCAT_PORT
              value: {{ .Values.confluence.ports.http | quote }}
            {{ if .Values.ingress.host }}
            - name: ATL_PROXY_NAME
              value: {{ .Values.ingress.host | quote }}
            - name: ATL_PROXY_PORT
              value: {{ include "confluence.ingressPort" . | quote }}
            {{ end }}
            - name: ATL_TOMCAT_ACCESS_LOG
              value: {{ .Values.confluence.accessLog.enabled | quote }}
            - name: UMASK
              value: {{ .Values.confluence.umask | quote }}
            - name: SET_PERMISSIONS
              value: {{ .Values.confluence.setPermissions | quote }}
            - name: ATL_PRODUCT_HOME_SHARED
              value: {{ .Values.volumes.sharedHome.mountPath | quote }}
            - name: JVM_SUPPORT_RECOMMENDED_ARGS
              valueFrom:
                configMapKeyRef:
                  key: additional_jvm_args
                  name: {{ include "common.names.fullname" . }}-jvm-config
            {{- include "confluence.clusteringEnvVars" . | nindent 12 }}
            {{- include "confluence.databaseEnvVars" . | nindent 12 }}
            {{ with .Values.confluence.license.secretName }}
            - name: ATL_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: {{ $.Values.confluence.license.secretKey }}
            {{ end }}
            - name: JVM_MINIMUM_MEMORY
              valueFrom:
                configMapKeyRef:
                  key: min_heap
                  name: {{ include "common.names.fullname" . }}-jvm-config
            - name: JVM_MAXIMUM_MEMORY
              valueFrom:
                configMapKeyRef:
                  key: max_heap
                  name: {{ include "common.names.fullname" . }}-jvm-config
            - name: JVM_RESERVED_CODE_CACHE_SIZE
              valueFrom:
                configMapKeyRef:
                  key: reserved_code_cache
                  name: {{ include "common.names.fullname" . }}-jvm-config
            {{- include "confluence.additionalEnvironmentVariables" . | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", {{ .Values.confluence.shutdown.command | quote }}]
        {{- include "fluentd.container" . | nindent 8 }}
        {{- include "confluence.additionalContainers" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.confluence.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName  | quote }}
      {{- end }}
      volumes:
        {{- range $i, $n := .Values.additionalFiles }}
        - name: {{ .name }}-{{$i}}
          {{ .type }}:
            {{ if hasPrefix .type "secret" }}{{ .type}}Name{{ else }}name{{ end }}: {{ .name }}
            items:
              - key: {{ .key }}
                path: {{ .key }}
        {{ end }}
        {{- range $i, $key := .Values.additionalConfigMaps }}
        {{- with $ }}
        {{- range $key.keys }}
        - name: {{ .fileName | replace "_" "-" | replace "." "-" }}
          configMap:
            name: {{ include "common.names.fullname" $ }}-{{ $key.name }}
            {{- if .defaultMode }}
            defaultMode: {{ .defaultMode }}
            {{- end }}
            items:
              - key: {{ .fileName }}
                path: {{ .fileName }}
            {{- end }}
        {{ end }}
        {{- end }}
        {{ include "confluence.volumes" . | nindent 8 }}
        {{ include "fluentd.config.volume" . | nindent 8 }}
        {{ include "common.jmx.config.volume" . | nindent 8 }}
  {{ include "confluence.volumeClaimTemplates" . | nindent 2 }}
