{{ if .Values.synchrony.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "synchrony.fullname" . }}
  labels:
    {{- include "synchrony.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.synchrony.replicaCount }}
  serviceName: {{ include "synchrony.fullname" . }}
  selector:
    matchLabels:
      {{- include "synchrony.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config-jvm: {{ include (print $.Template.BasePath "/synchrony-start-script.yaml") . | sha256sum }}
        {{- if .Values.synchrony.podAnnotations }}
        {{- include "synchrony.podAnnotations" . | nindent 8 }}
        {{- else }}
        {{- include "confluence.podAnnotations" . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "synchrony.selectorLabels" . | nindent 8 }}
        {{- include "confluence.podLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "confluence.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.synchrony.shutdown.terminationGracePeriodSeconds }}
      {{- if .Values.synchrony.securityContextEnabled }}
      {{- with .Values.synchrony.securityContext }}
      securityContext:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      hostAliases:
        {{- include "confluence.additionalHosts" . | nindent 8 }}
      {{- if .Values.synchrony.additionalCertificates.secretName }}
      initContainers:
      - name: import-certs
        image: {{ include "confluence.image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - name: keystore
            mountPath: /var/ssl
          - name: certs
            mountPath: /tmp/crt
        command: ["/bin/bash"]
        args: ["-c", {{ include "synchrony.addCrtToKeystoreCmd" . }}]
      {{- end }}
      containers:
        - name: synchrony
          image: {{ include "confluence.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/scripts/start-synchrony.sh"]
          volumeMounts:
            {{- include "synchrony.volumeMounts" . | nindent 12 }}
            {{- include "synchrony.additionalVolumeMounts" . | nindent 12 }}
            {{- include "synchrony.additionalLibraries" . | nindent 12 }}
            - mountPath: /scripts
              name: entrypoint-script
          ports:
            - name: http
              containerPort: {{ .Values.synchrony.ports.http }}
              protocol: TCP
            - name: hazelcast
              containerPort: {{ .Values.synchrony.ports.hazelcast }}
              protocol: TCP
            {{- include "synchrony.additionalPorts" . | nindent 12 }}
          readinessProbe:
            httpGet:
              port: {{ .Values.synchrony.ports.http }}
              path: {{ .Values.synchrony.readinessProbe.healthcheckPath }}
            initialDelaySeconds: {{ .Values.synchrony.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.synchrony.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.synchrony.readinessProbe.failureThreshold }}
          {{- with .Values.synchrony.containerSecurityContext }}
          securityContext:
          {{- toYaml . | nindent 12}}
          {{- end}}
          {{- with .Values.synchrony.resources.container }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: SET_PERMISSIONS
              value: {{ .Values.synchrony.setPermissions | quote }}
            - name: SYNCHRONY_BIND
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SYNCHRONY_SERVICE_URL
            {{ if .Values.ingress.https }}
              value: "https://{{ .Values.ingress.host }}/synchrony"
            {{ else }}
              value: "http://{{ .Values.ingress.host }}/synchrony"
            {{- end }}
            {{- include "synchrony.databaseEnvVars" . | nindent 12 }}
            {{- include "synchrony.clusteringEnvVars" . | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.synchrony.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      volumes:
        - name: entrypoint-script
          configMap:
            name: {{ include "synchrony.fullname" . }}-entrypoint
            defaultMode: {{ .Values.volumes.defaultPermissionsMode | default "484" }}
        {{ include "synchrony.volumes" . | nindent 8 }}
  {{ include "synchrony.volumeClaimTemplates" . | nindent 2 }}
{{ end }}
