apiVersion: v2
name: jira
description: A chart for installing Jira Data Center on Kubernetes
type: application
version: '2.0.1'
appVersion: 10.3.6
kubeVersion: ">=1.21.x-0"
keywords:
- Jira
- Jira Software
- Jira Server
- Jira Data Center
- Jira DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/jira-software.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-jira/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Update appVersions for DC apps (#1006)"

dependencies:
- name: common
  version: 1.2.7
  repository: https://atlassian.github.io/data-center-helm-charts
