apiVersion: v2
name: jira
description: A chart for installing Jira DC on Kubernetes
type: application
version: 0.1.0
appVersion: 8.13.0-jdk11
kubeVersion: >= 1.17.x
keywords:
  - Jira
  - Jira Software
  - Jira Server
  - Jira Data Center
  - Atlassian
home: https://github.com/atlassian-labs/data-center-helm-charts
sources:
  - https://github.com/atlassian-labs/data-center-helm-charts
deprecated: false
