apiVersion: v2
name: jira
description: A chart for installing Jira Data Center on Kubernetes
type: application
version: 1.2.0
appVersion: 8.20.7-jdk11
kubeVersion: ">=1.19.x-0"
keywords:
  - Jira
  - Jira Software
  - Jira Server
  - Jira Data Center
  - Jira DC
  - Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/jira-software.svg
sources:
  - https://github.com/atlassian/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-atlassian-jira/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - kind: added
      description: Add new feature additionalPorts (for jmx-monitoring) 
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/353
    - kind: changed
      description: Set ActiveProcessorCount automatically based on Values.<product>.resources.container.requests.cpu
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/352
    - kind: added
      description: Added topologySpreadConstraints to products
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/351
    - kind: changed
      description: Define podAnnotations as template to allow overrides
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/341
    - kind: added
      description: Added new feature to define loadBalancerIP
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/365
    - kind: added
      description: Added new feature podLabels
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/364
    - kind: added
      description: Added new feature additionalVolumeClaimTemplates and provided example in documentation
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/334
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/368
    - kind: added
      description: Added service account annotation
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/363
    - kind: changed
      description: Updated Atlassian charts to use common definitions
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/303
    - kind: changed
      description: Improvements on documentation
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/370
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/357
    - kind: changed
      description: Jira DC updated to 8.20.5 version (LTS)
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/378
dependencies:
  - name: common
    version: 1.0.0
    repository: https://atlassian.github.io/data-center-helm-charts
