apiVersion: v2
name: jira
description: A chart for installing Jira Data Center on Kubernetes
type: application
version: 0.15.0
appVersion: 8.13.9-jdk11
kubeVersion: ">=1.19.x-0"
keywords:
  - Jira
  - Jira Software
  - Jira Server
  - Jira Data Center
  - Jira DC
  - Atlassian
home: https://www.atlassian.com/software/jira
icon: https://atlassian-labs.github.io/data-center-helm-charts/icons/jira-software.svg
sources:
  - https://github.com/atlassian-labs/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-atlassian-jira/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: added
      description: Add Service annotations
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/209
    - kind: added
      description: Add support for providing a custom fluentd start command
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/218
    - kind: changed
      description: Renamed the 'master' branch to 'main'
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/232
    - kind: changed
      description: Update eks cluster yaml
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/227
    - kind: changed
      description: Improve documentation
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/206
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/222
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/223
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/228
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/229
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/231
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/233
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/235