apiVersion: v2
name: jira
description: A chart for installing Jira Data Center on Kubernetes
type: application
version: 1.15.3
appVersion: 9.4.9
kubeVersion: ">=1.21.x-0"
keywords:
- Jira
- Jira Software
- Jira Server
- Jira Data Center
- Jira DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/jira-software.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-jira/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Decouple server and jmx annotations (#654)"
    - "Disable startup probes by default (#653)"

dependencies:
- name: common
  version: 1.2.3
  repository: https://atlassian.github.io/data-center-helm-charts
