apiVersion: v2
name: jira
description: A chart for installing Jira Data Center on Kubernetes
type: application
version: 0.13.0
appVersion: 8.13.7-jdk11
kubeVersion: ">=1.19.x-0"
keywords:
  - Jira
  - Jira Software
  - Jira Server
  - Jira Data Center
  - Jira DC
  - Atlassian
home: https://www.atlassian.com/software/jira
icon: https://atlassian-labs.github.io/data-center-helm-charts/icons/jira-software.svg
sources:
  - https://github.com/atlassian-labs/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-atlassian-jira/
deprecated: false
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Added Jira Proxy information to helm chart
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/202
    - kind: changed
      description: Volume docs updates
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/188