apiVersion: v1
kind: Service
metadata:
  name: {{ include "jira.fullname" . }}
  labels:
    {{- include "jira.labels" . | nindent 4 }}
spec:
  type: {{ .Values.jira.service.type }}
  ports:
    - port: {{ .Values.jira.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jira.selectorLabels" . | nindent 4 }}
