apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "jira.fullname" . }}
  labels:
    {{- include "jira.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "jira.fullname" . }}
  selector:
    matchLabels:
      {{- include "jira.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jira.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "jira.serviceAccountName" . }}
      terminationGracePeriodSeconds: 1
{{ if .Values.jira.securityContext.enabled }}
      securityContext:
        # This is intended to ensure that the shared-home volume is group-writeable by the GID used by the Jira container.
        # However, this doesn't appear to work for NFS volumes due to a K8s bug: https://github.com/kubernetes/examples/issues/260
        fsGroup: {{ .Values.jira.securityContext.gid }}
{{ end }}
      {{- with .Values.additionalInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "jira.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{ if .Values.ingress.https }}
            - name: ATL_TOMCAT_SCHEME
              value: "https"
            - name: ATL_TOMCAT_SECURE
              value: "true"
              {{ end }}
            {{- include "jira.databaseEnvVars" . | nindent 12 }}
            {{- include "jira.clusteringEnvVars" . | nindent 12 }}
            {{ with .Values.jira.license.secretName }}
            - name: JIRA_SETUP_LICENSE
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: {{ $.Values.jira.license.secretKey }}
            {{ end }}
            - name: JIRA_SHARED_HOME
              value: {{ .Values.volumes.sharedHome.mountPath | quote }}
            - name: JVM_SUPPORT_RECOMMENDED_ARGS
              valueFrom:
                configMapKeyRef:
                  key: additional_jvm_args
                  name: {{ include "jira.fullname" . }}-jvm-config
            - name: JVM_MINIMUM_MEMORY
              valueFrom:
                configMapKeyRef:
                  key: min_heap
                  name: {{ include "jira.fullname" . }}-jvm-config
            - name: JVM_MAXIMUM_MEMORY
              valueFrom:
                configMapKeyRef:
                  key: max_heap
                  name: {{ include "jira.fullname" . }}-jvm-config
            - name: JVM_RESERVED_CODE_CACHE_SIZE
              valueFrom:
                configMapKeyRef:
                  key: reserved_code_cache
                  name: {{ include "jira.fullname" . }}-jvm-config
            {{- with .Values.jira.additionalEnvironmentVariables }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.jira.ports.http }}
              protocol: TCP
          readinessProbe:
            httpGet:
              port: {{ .Values.jira.ports.http }}
              path: /status
            initialDelaySeconds: {{ .Values.jira.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.jira.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.jira.readinessProbe.failureThreshold }}
          {{- with .Values.jira.resources.container }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- include "jira.volumeMounts" . | nindent 12 }}
            {{- with .Values.jira.additionalVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- include "jira.additionalLibraries" . | nindent 12 }}
            {{- include "jira.additionalBundledPlugins" . | nindent 12 }}
        {{- include "fluentd.container" . | nindent 8 }}
        {{- with .Values.additionalContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{ include "jira.volumes" . | nindent 8 }}
        {{ include "fluentd.config.volume" . | nindent 8 }}
  {{ include "jira.volumeClaimTemplates" . | nindent 2 }}