{{- if .Values.ingress.create }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "crowd.fullname" . }}
  labels:
    {{- include "crowd.labels" . | nindent 4 }}
  annotations:
    {{- /* the default can be removed in v2.0.0 */ }}
    "kubernetes.io/ingress.class": {{ default "nginx" .Values.ingress.className }}
    {{ if .Values.ingress.nginx }}
    "nginx.ingress.kubernetes.io/affinity": "cookie"
    "nginx.ingress.kubernetes.io/affinity-mode": "persistent"
    "nginx.ingress.kubernetes.io/proxy-body-size": {{ .Values.ingress.maxBodySize }}
    "nginx.ingress.kubernetes.io/proxy-connect-timeout": "60"
    "nginx.ingress.kubernetes.io/proxy-read-timeout": "60"
    "nginx.ingress.kubernetes.io/proxy-send-timeout": "60"
    {{- end }}
    {{- with .Values.ingress.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{ if and (.Values.ingress.tlsSecretName) (.Values.ingress.host) }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
{{ end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "crowd.fullname" . }}
                port:
                  number: {{ $.Values.crowd.service.port }}
{{ end }}
