apiVersion: v2
name: bamboo
description: A chart for installing Bamboo Data Center on Kubernetes
type: application
version: 1.0.0
appVersion: 8.0  # TODO: THIS NEEDS TO BE CONFIRMED 
kubeVersion: ">=1.19.x-0"
keywords:
  - Bamboo
  - Bamboo Server
  - Bamboo Data Center
  - Bamboo DC
  - Atlassian
home: https://www.atlassian.com/software/bamboo
icon: https://atlassian-labs.github.io/data-center-helm-charts/icons/bamboo.svg
sources:
  - https://github.com/atlassian-labs/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-bamboo-server
  - https://bitbucket.org/atlassian-docker/docker-bamboo-agent-base
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "true"