apiVersion: v2
name: bamboo
description: A chart for installing Bamboo Data Center on Kubernetes
type: application
version: '2.0.10'
appVersion: 12.1.1
kubeVersion: ">=1.21.x-0"
keywords:
- Bamboo
- Bamboo Server
- Bamboo Data Center
- Bamboo DC
- Atlassian
home: https://www.atlassian.com/software/bamboo
icon: https://atlassian.github.io/data-center-helm-charts/icons/bamboo.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-bamboo-server
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Add Gateway API support via HTTPRoute resources"
    - "Gateway API provides modern alternative to Ingress"
dependencies:
- name: common
  version: 1.2.7
  repository: https://atlassian.github.io/data-center-helm-charts
