apiVersion: v2
name: bamboo
description: A chart for installing Bamboo Data Center on Kubernetes
type: application
version: 1.15.0
appVersion: 9.3.1
kubeVersion: ">=1.21.x-0"
keywords:
- Bamboo
- Bamboo Server
- Bamboo Data Center
- Bamboo DC
- Atlassian
home: https://www.atlassian.com/software/bamboo
icon: https://atlassian.github.io/data-center-helm-charts/icons/bamboo.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-bamboo-server
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Add PodDisruptionBudget to Atlassian DC Helm Charts (#636)"
    - "Add annotations to Grafana dashboards ConfigMaps (#637)"
    - "Add additional ConfigMaps to Helm Charts (#635)"
dependencies:
- name: common
  version: 1.2.3
  repository: https://atlassian.github.io/data-center-helm-charts
