apiVersion: v2
name: bamboo
description: A chart for installing Bamboo Data Center on Kubernetes
type: application
version: 0.0.1
appVersion: 8.0.4-jdk11
kubeVersion: ">=1.19.x-0"
keywords:
  - Bamboo
  - Bamboo Server
  - Bamboo Data Center
  - Bamboo DC
  - Atlassian
home: https://www.atlassian.com/software/bamboo
icon: https://atlassian.github.io/data-center-helm-charts/icons/bamboo.svg
sources:
  - https://github.com/atlassian/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-bamboo-server
deprecated: false
dependencies:
  - name: common
    version: 1.0.0
    repository: "file://../common"
